#!/usr/bin/env bash
# configuring subdomains

domain_lookup()
{
	local domain="$1"
	local subdomain="$2"
	local ip=$(dig "$subdomain.$domain" +short)
	local dns_record=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/{getline; print $4')
	echo "The subdomain $subdomain is a $dns_record record and points to $ip"
}


if [ -z "$2" ]; then
	domain_lookup "$1" www
	domain_lookup "$" lb-01
	domain_lookup "$1" web-01
	domain_lookup "$1" web-02
else
	domain_lookup "$1" "$2"
fi
