#!/usr/bin/env bash
# transfers a file from a client to a server

if [ "$#" -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi

file_path="$1"
ip_server="$2"
username="$3"
pkey_path="$4"

scp -o StrictHostKeyChecking=no -i "$pkey_path" "$file_path" "$username@$ip_server":~/
