#!/usr/bin/env bash
# configures a new Ubuntu machine (install nginx -> port 80)

apt-get update
apt-get install -y nginx

service nginx start
echo "Hello World!" > /var/www/html/index.html
service nginx restart
