#!/usr/bin/env bash
# configures a new Ubuntu machine (install nginx -> port 80)

apt-get update
apt-get install -y nginx

service nginx start
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/my_404.html

echo "server {
	listen 80;
	listen [::]:80 default_server;
	root /var/www/html;
	error_page 404 /my_404.html;
	add_header X-Served-By $HOSTNAME;

	location /redirect_me {
		return 301;
	}

	location /404 {
		root /var/www/html;
		internal;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
