#!/usr/bin/env bash
# install HAproxy on a load balancing server

apt-get update
apt-get install -y haproxy

#service haproxy start

echo "global
        log 127.0.0.1 local0 notice
        maxconn 1024
        user haproxy
        group haproxy
defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
	retries 3
	option http-server-close
	option http-pretend-keepalive
	option redispatch
        timeout connect 5000
        timeout client  50000
        timeout server  50000
frontend web_frontend
        bind :80
        default_backend my_servers
backend my_servers
        balance roundrobin
        server 310495-web-01 54.157.128.199 check
        server 310495-web-02 54.90.50.235 check" > /etc/haproxy/haproxy.cfg

echo 'ENABLED=1' > /etc/default/haproxy

service haproxy restart
