#!/usr/bin/env bash
# y u no love me?

count=1
pid=$(pgrep -f "100-process_and_pid_file")
handle_term() {
	echo "I hate the kill commaned"
	rm /var/run/myscript.pid
	pkill "$pid"
}

handle_int() {
	echo "Y U no love me?!"
}

handle_quit() {
	rm /var/run/myscript.pid
	kill -3 "$pid"
}

touch /var/run/myscript.pid
trap 'handle_term' SIGTERM
trap 'handle_int' SIGINT
trap 'handle_quit' SIGQUIT

until [ $count -eq 0 ]; do
	echo "To infinity and beyond"
	((count++))
done
