#!/usr/bin/env bash
# y u no love me?

file="/var/run/myscript.pid"
count=1
pid=$(pgrep -f "100-process_and_pid_file")

echo $$ > $file
handle_term() {
	echo "I hate the kill commaned"
	rm $file
	pkill "$pid"
}

handle_int() {
	echo "Y U no love me?!"
}

handle_quit() {
	rm $file
	kill -3 "$pid"
}

trap 'handle_term' SIGTERM
trap 'handle_int' SIGINT
trap 'handle_quit' SIGQUIT

until [ $count -eq 0 ]; do
	echo "To infinity and beyond"
	((count++))
done
